### ISSUE TITLE
Add option to configure IPv6 default route

### ISSUE THREAD

**Issue by xen0l** [olbohlen/sysding#1]
There is no way how to pass -f iner6/-inet6 to setup_route and has to be done as a custom command. It would be nice to have this supported.

**Comment by olbohlen** [comment]
fix is prepared

**Comment by olbohlen** [comment]
this is fixed, just use the setup_route method. if it finds a colon in the argument, it will enforce -inet6.
If you use hostnames, the route command by itself will figure out that is has to use -inet6
